### ISSUE TITLE
"Fork me on GitHub" link is busted ;)

### ISSUE THREAD

**Issue by justinclift** [micromaomao/maowtm.org#1]
Looking through the About page on your website, the "Fork me on GitHub" link (top right) is broken.

It goes to:

&nbsp; &nbsp; https://github.com/micromaomao/maowtm.org/blob/master/static/main_site/about.js

But that gives a 404. :wink:

**Comment by micromaomao** [comment]
Oh
Thanks...

Looks like I merged a new version of my website on `master`, but haven't pushed it to the server because I haven't finished. Maybe I shouldn't merge it into master yet...

BTW, <del>**THERE ARE ACTUAL PEOPLE LOOKING MY WEBSITE LOL**<del>( thought no one will ever come to that website again 😂 )

**Comment by micromaomao** [comment]
Fixed and deployed.

Thanks for checking out my website :D

**Comment by justinclift** [comment]
Heh Heh Heh :wink:

Yep, it's confirmed working here now too.

And yeah, you starred our [GitHub repo](github.com/sqlitebrowser/sqlitebrowser) a little earlier on today... and I was bored while waiting for our new "3.9.0 beta1" packages to finish building... so... well... yeah... 😀

**Comment by micromaomao** [comment]
@justinclift I was checking to see if the `cannot start a transaction within a transaction` error on importing sql file had a issue opened there on GitHub... Look like it's solved a month ago, so I was wondering when will you put a new version into the Arch repository because the software on my Arch linux box still have this issue.

**Comment by micromaomao** [comment]
Also, your hyperlink isn't working...

**Comment by justinclift** [comment]
Thanks, hyperlink fixed. :smile:

**Comment by justinclift** [comment]
For the Arch package, it's not something we build ourselves.

__But__, it's super easy to build an updated version yourself.  It should take less than 5 minutes, and that's including reading the instructions here:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#generic-linux-and-freebsd

**Comment by justinclift** [comment]
There seems to be a "sqlitebrowser-git" package too.  I'm not sure what that does, but if it compiles from our latest source code that is probably a better option too:

&nbsp; &nbsp; https://aur.archlinux.org/packages/sqlitebrowser-git/

**Comment by justinclift** [comment]
If none of that helps, we should be releasing "3.9.0" next week.  I'm making our "3.9.0 beta1" windows and OSX packages today.

**Comment by justinclift** [comment]
Does any of the above help?

**Comment by micromaomao** [comment]
Oh yes, just realized that Arch build these package themselves ( almost ).

The `-git` package is from Aur, which I basically need to package it myself with `makepkg` ( and is not considered very "secure" by me really... for some reason. )

Maybe I'll wait for the release "3.9.0 beta1".

**Comment by justinclift** [comment]
Sure, no worries at all. :smile:

3.9.0 has a lot of bug fixes in it compared to 3.9.0.  It's not perfect, but it should be a lot better for people to use. :smile:

**Comment by micromaomao** [comment]
Thanks...

Going to sleep now ( UTC+8 ), bye :D
